# Generated by Django 3.0.6 on 2020-05-12 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_libro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='nombre',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='autor',
            name='nombre',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='editorial',
            name='nombre',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='genero',
            name='nombre',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='libro',
            name='cant_capitulos',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='libro',
            name='cant_paginas',
            field=models.PositiveIntegerField(),
        ),
        migrations.RemoveField(
            model_name='libro',
            name='genero',
        ),
        migrations.AddField(
            model_name='libro',
            name='genero',
            field=models.ManyToManyField(to='gestion_libro.Genero'),
        ),
    ]
