# Generated by Django 3.0.5 on 2020-05-16 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_libro', '0003_libro_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='pdf'),
        ),
    ]
