# Generated by Django 3.0.5 on 2020-05-16 20:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_libro', '0004_auto_20200516_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor',
            name='nombre',
            field=models.CharField(default='', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='editorial',
            name='nombre',
            field=models.CharField(default='', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='genero',
            name='nombre',
            field=models.CharField(default='', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='libro',
            name='ISBN',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='libro',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='pdf', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
    ]
