# Generated by Django 3.0.5 on 2020-05-19 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_libro', '0005_auto_20200516_2033'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='static/foto_libro'),
        ),
    ]
