# Generated by Django 3.0.6 on 2020-06-16 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_libro', '0006_libro_foto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libro',
            name='cant_capitulos',
        ),
        migrations.AddField(
            model_name='libro',
            name='capitulos',
            field=models.TextField(blank=True, help_text="Por favor separar cada pagina por una ',' ej: 10,30,35,102"),
        ),
        migrations.AddField(
            model_name='libro',
            name='fecha_vencimiento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
