# Generated by Django 3.0.6 on 2020-06-16 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_libro', '0007_auto_20200616_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='ocultar',
            field=models.BooleanField(default=False),
        ),
    ]
