# Generated by Django 3.0.6 on 2020-06-20 22:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_libro', '0008_libro_ocultar'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='nuevo_capitulo',
            field=models.FileField(blank=True, null=True, upload_to='pdf/capitulos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
    ]
