# Generated by Django 3.0.6 on 2020-06-20 23:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_libro', '0009_libro_nuevo_capitulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='nuevo_capitulo',
            field=models.FileField(blank=True, null=True, upload_to='static/pdf/capitulos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
        migrations.AlterField(
            model_name='libro',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='static/pdf', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
    ]
