# Generated by Django 3.0.6 on 2020-07-05 22:18

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_libro', '0010_auto_20200620_2350'),
    ]

    operations = [
        migrations.RenameField(
            model_name='libro',
            old_name='nuevo_capitulo',
            new_name='extender_libro',
        ),
        migrations.RemoveField(
            model_name='libro',
            name='capitulos',
        ),
        migrations.CreateModel(
            name='Capitulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=50, unique=True)),
                ('pdf', models.FileField(blank=True, null=True, upload_to='static/pdf/capitulos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('libro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion_libro.Libro')),
            ],
        ),
    ]
