# Generated by Django 3.0.6 on 2020-07-05 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_libro', '0011_auto_20200705_2218'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='capitulo',
            name='nombre',
        ),
    ]
