# Generated by Django 3.0.6 on 2020-07-05 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_libro', '0012_remove_capitulo_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='capitulo',
            name='numero_de_capitulo',
            field=models.CharField(default='', max_length=50),
        ),
    ]
