# Generated by Django 3.0.6 on 2020-07-05 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_libro', '0013_capitulo_numero_de_capitulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capitulo',
            name='numero_de_capitulo',
            field=models.IntegerField(),
        ),
    ]
