# Generated by Django 3.0.6 on 2020-07-05 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_libro', '0014_auto_20200705_2332'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libro',
            name='extender_libro',
        ),
    ]
