# Generated by Django 3.0.6 on 2020-07-07 19:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_libro', '0015_remove_libro_extender_libro'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='es_capitulado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='capitulo',
            name='numero_de_capitulo',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
