# Generated by Django 3.0.6 on 2020-07-07 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_libro', '0017_libro_numero_de_capitulos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capitulo',
            name='libro',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion_libro.Libro'),
        ),
    ]
