# Generated by Django 3.0.6 on 2020-07-09 19:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_libro', '0019_auto_20200708_0355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='numero_de_capitulos',
            field=models.IntegerField(default=0, editable=False, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='libro',
            name='pdf',
            field=models.FileField(blank=True, editable=False, null=True, upload_to='static/pdf', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
    ]
