# Generated by Django 3.0.6 on 2020-07-10 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_libro', '0020_auto_20200709_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='es_capitulado',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
