# Generated by Django 3.0.6 on 2020-07-11 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_pago', '0002_auto_20200607_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarjeta',
            name='numero',
            field=models.IntegerField(null=True),
        ),
    ]
