# Generated by Django 3.0.6 on 2020-07-11 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_pago', '0003_auto_20200711_0025'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarjeta',
            name='expira',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tarjeta',
            name='cvc',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tarjeta',
            name='numero',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
