# Generated by Django 3.0.5 on 2020-05-16 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_noticia', '0002_auto_20200511_2214'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='fecha_de_creacion',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='cuerpo',
            field=models.TextField(blank=True),
        ),
    ]
