# Generated by Django 3.0.5 on 2020-05-16 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_noticia', '0003_auto_20200516_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='fecha_de_creacion',
            field=models.DateField(),
        ),
    ]
