# Generated by Django 3.0.6 on 2020-06-16 21:19

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_libro', '0008_libro_ocultar'),
        ('gestion_noticia', '0005_trailer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trailers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('cuerpo', models.TextField(blank=True)),
                ('pdf', models.FileField(blank=True, null=True, upload_to='static/video_trailer', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4'])])),
                ('fecha_de_creacion', models.DateField()),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_libro.Libro')),
            ],
        ),
        migrations.DeleteModel(
            name='Trailer',
        ),
    ]
