# Generated by Django 3.0.6 on 2020-06-16 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_noticia', '0007_auto_20200616_1821'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trailer',
            old_name='pdf',
            new_name='video',
        ),
    ]
