# Generated by Django 3.0.6 on 2020-07-05 00:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_noticia', '0008_auto_20200616_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trailer',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='static/video_trailer', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'webm'])]),
        ),
    ]
