# Generated by Django 3.0.5 on 2020-05-16 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_usuario', '0014_auto_20200511_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='nickname',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
