# Generated by Django 3.0.5 on 2020-05-19 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_usuario', '0015_auto_20200516_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='foto_perfil',
            field=models.ImageField(blank=True, default='static/foto_perfil/default.jpg', null=True, upload_to='static/foto_perfil'),
        ),
    ]
