# Generated by Django 3.0.5 on 2020-05-19 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_usuario', '0016_profile_foto_perfil'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='foto_perfil',
            new_name='foto',
        ),
    ]
