# Generated by Django 3.0.5 on 2020-05-20 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_usuario', '0017_auto_20200519_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='soyPrincipal',
            field=models.BooleanField(default=False),
        ),
    ]
