# Generated by Django 3.0.5 on 2020-05-20 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_usuario', '0018_auto_20200520_0107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='foto',
            field=models.ImageField(blank=True, default='static/foto_perfil/2.jpg', null=True, upload_to='static/foto_perfil'),
        ),
    ]
