# Generated by Django 3.0.5 on 2020-05-20 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_usuario', '0019_auto_20200520_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='foto',
            field=models.ImageField(blank=True, default='static/foto_perfil/default.jpg', null=True, upload_to='static/foto_perfil'),
        ),
    ]
