# Generated by Django 3.0.6 on 2020-07-05 00:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_libro', '0010_auto_20200620_2350'),
        ('gestion_usuario', '0020_auto_20200520_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='libro',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion_libro.Libro'),
        ),
        migrations.CreateModel(
            name='Leidos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now=True)),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_libro.Libro')),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_usuario.Profile')),
            ],
        ),
    ]
