# Generated by Django 3.0.6 on 2020-07-08 03:55

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_libro', '0019_auto_20200708_0355'),
        ('gestion_usuario', '0021_auto_20200705_0028'),
    ]

    operations = [
        migrations.CreateModel(
            name='CapitulosLeidos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_capitulo_leido', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_libro.Libro')),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_usuario.Profile')),
            ],
        ),
    ]
