# Generated by Django 3.0.6 on 2020-07-09 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_libro', '0019_auto_20200708_0355'),
        ('gestion_usuario', '0022_capitulosleidos'),
    ]

    operations = [
        migrations.AddField(
            model_name='capitulosleidos',
            name='capitulo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion_libro.Capitulo'),
        ),
    ]
