# Generated by Django 3.0.6 on 2020-07-09 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_usuario', '0022_capitulosleidos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='puntaje',
            name='estrellas',
        ),
        migrations.AddField(
            model_name='puntaje',
            name='like',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
