# Generated by Django 3.0.6 on 2020-07-09 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_usuario', '0023_auto_20200709_1440'),
        ('gestion_usuario', '0023_capitulosleidos_capitulo'),
    ]

    operations = [
    ]
